######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 27 17:15:07 2016
######################################################################

TEMPLATE = app
TARGET = twitter
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += datetime.h interface.h tweet.h twiteng.h user.h
SOURCES += datetime.cpp interface.cpp main.cpp tweet.cpp twiteng.cpp user.cpp
